#!/usr/bin/env bash
# Dig and awk given domain name
dig_domain(){
    if [ $# -eq 1 ]
    then
        domain=$1
        subdomain=('www' 'lb-01' 'web-01' 'web-02')

        i=0
        while [ $i -lt ${#subdomain[*]} ]
        do
            #record_type=$(dig "${subdomain[$i]}.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
            #destination=$(dig "${subdomain[$i]}.$domain" | awk '/ANSWER SECTION/ {getline; print $5}')
            
            # Run the dig command and capture the full output
            dig_res=$(dig "${subdomain[$i]}.$domain")

            # Extract record type and destination from the ANSWER SECTION
            record_type=$(echo "$dig_res" | awk '/ANSWER SECTION/ {getline; print $4}')
            destination=$(echo "$dig_res" | awk '/ANSWER SECTION/ {getline; print $5}')
            echo "The subdomain ${subdomain[$i]} is a $record_type record and points to $destination"
            i=$((i + 1))
        done
    elif [ $# -eq 2 ]
    then
        domain=$1
        subd=$2
    
        #record_type=$(dig "$subd.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
        #destination=$(dig "$subd.$domain" | awk '/ANSWER SECTION/ {getline; print $5}')
        #echo "The subdomain ${subd} is a $record_type record and points to $destination"
        # Run the dig command and capture the full output
        dig_res=$(dig "$subd.$domain")

        # Extract record type and destination from the ANSWER SECTION
        record_type=$(echo "$dig_res" | awk '/ANSWER SECTION/ {getline; print $4}')
        destination=$(echo "$dig_res" | awk '/ANSWER SECTION/ {getline; print $5}')

        # Print the information
        echo "The subdomain $subd is a $record_type record and points to $destination"

    fi
}

dig_domain "$@"
