#!/usr/bin/env bash
# Transfer a file to server
if [[ $# -gt 3 ]]
then
    source_f=$1
    dest_ip=$2
    username=$3
    key_path=$4

    scp -i "$key_path" -o StrictHostKeyChecking=No "$source_f" "$username@$dest_ip" "$HOME/"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
