#!/usr/bin/env bash
# Transfer a file to server
if [[ $# -gt 3 ]]
then
    source_f=$1
    dest_ip=$2
    username=$3
    key_path=$4

    scp -i "$key_path" -o StrictHostKeyChecking=No "$username@$dest_ip" "$source_f" "$HOME/"
    echo "$key_path $dest_ip $username $source_f"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
