#!/usr/bin/env bash
# Configure Nginx server to redirect to another page
apt-get update -y
apt-get install nginx -y

service nginx start

echo "Hello World!" | tee /var/www/html/index.html

# Replace config line here
redirect_block="\tserver_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
file_path="/etc/nginx/sites-available/default"

# Duplicate config
cp "$file_path" "/etc/nginx/default.orig"

# Search and replace
# sed -i "/server_name _;/a $redirect_block" "$file_path"
sed -i "s|server_name _;|$redirect_block|" "$file_path"

nginx -t
nginx -s reload
