#!/usr/bin/env bash
# Backup the database
password=$1

# Dump it
mysqldump -p"$password" --all-databases > backup.sql

# Archive it
tar -czf "$(date '+%d')-$(date '+%m')-$(date '+%Y')".tar.gz backup.sql
