#!/usr/bin/env bash
# Why you no love me
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; kill -9 $$;' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; kill -9 $$' SIGQUIT

echo $$ > '/var/run/myscript.pid'

while true;do
echo "To infinity and beyond"
sleep 2
done
